general:
  seed: 42
  start: "2024-01-01"
  end: "2030-01-01"
  timeframe: "1m"
  capital: 10000.0
  symbols: ["BTC/USDT"]

data:
  provider: ccxt
  steps_per_bar: 20
  drift: 0.0
  volatility: 0.02

broker:
  fee_bps: 10
  slippage_bps: 5

risk:
  max_position_pct: 0.2
  max_daily_drawdown_pct: 5

strategy:
  name: nof1_baseline
  params:
    rsi_period: 14
    rsi_buy: 30
    rsi_sell: 70
    ema_fast: 12
    ema_slow: 26
    atr_period: 14
    volatility_floor: 0.002

ensemble:
  weights:
    llm: 1.0
    nof1_baseline: 0.0
  llm_overlay:
    enabled: false

backtest:
  report:
    output_dir: logs/reports


