# Sample config for paper trading with random-walk data

general:
  seed: 42
  start: "2024-01-01"
  end: "2024-03-01"
  timeframe: "5m"
  capital: 10000.0
  symbols: ["BTC/USDT"]

data:
  provider: random_walk
  steps_per_bar: 20          # higher = smoother bars
  drift: 0.0
  volatility: 0.02           # daily-ish volatility proxy

broker:
  fee_bps: 10                # 0.10%
  slippage_bps: 5            # 0.05%

risk:
  max_position_pct: 0.2      # max 20% per symbol
  max_daily_drawdown_pct: 5

strategy:
  name: nof1_baseline
  params:
    rsi_period: 14
    rsi_buy: 30
    rsi_sell: 70
    ema_fast: 12
    ema_slow: 26
    atr_period: 14
    volatility_floor: 0.002  # ATR/price threshold

ensemble:
  weights:
    nof1_baseline: 1.0
  llm_overlay:
    enabled: false

backtest:
  report:
    output_dir: logs/reports
